export const REGISTER = "REGISTER";
export const LOGIN  = "LOGIN";
export const FAILURE = "FAILURE";
export const FETCH_USERSTATICS = "FETCH_USERSTATICS";
export const FETCH_ADMINUSERLIST = "FETCH_ADMINUSERLIST";
export const FETCH_QUESTIONANSWERLIST = "FETCH_QUESTIONANSWERLIST";
export const FETCH_ORDERDETAILSLIST = "FETCH_ORDERDETAILSLIST";